export const globalTrip = {
  trips: [
    {
      date: "20240929",
      desc1: "2024.09.29",
      desc2: "부암동 나들이",
      logo: require("@/assets/img/logo/20240929.png"),
      map: require("@/assets/img/map_20240929.png"),
      map2: undefined,
      buttonText1: undefined,
      buttonText2: undefined,
      drive: "http://naver.me/GTnQ1tj1",
      title: "등산 이후...\n들렀던 카페의 이름은~",
      radio: {
        v1: "백화밀",
        v2: "산모퉁이",
        v3: "맘스키친",
        v4: "생마차",
      },
      answer: "v1",
      answerTitle: "정답은 백화밀~~~☕",
      answerText: "가는 길이 험했던 카페..",
      errorTitle: "너무하네...🤨",
      errorText: "가는길이 험했잖아...",
    },
    {
      date: "20241005",
      desc1: "2024.10.05",
      desc2: "강북 나들이",
      logo: require("@/assets/img/logo/20241005.png"),
      map: require("@/assets/img/map_20241005.png"),
      map2: undefined,
      buttonText1: undefined,
      buttonText2: undefined,
      drive: "http://naver.me/5UEiY0Vg",
      title: "기억 하시나요?\n왕이 제향을 위해 걷는 길은~",
      radio: {
        v1: "신로",
        v2: "어로",
        v3: "향로",
      },
      answer: "v2",
      answerTitle: "정답입니다~🎉",
      answerText: "King's Road....",
      errorTitle: "이건 좀 어렵다~~🤔",
      errorText: "인스스에서 본거 같은.. ^__^",
    },
    {
      date: "20241013",
      desc1: "2024.10.13",
      desc2: "파주 출판도시 나들이",
      logo: require("@/assets/img/logo/20241013.png"),
      map: require("@/assets/img/map_20241013_1.png"),
      map2: require("@/assets/img/map_20241013_2.png"),
      buttonText1: "파주 경로도 궁금하다면?",
      buttonText2: "합정 경로도 궁금하다면?",
      drive: "http://naver.me/xLWf4P5G",
      title: "즐거운 교육시간 이후\n어느 숲으로 떠났을까요?",
      radio: {
        v1: "동물의숲",
        v2: "몽환의숲",
        v3: "지혜의숲",
      },
      answer: "v3",
      answerTitle: "너무 조용했던 지혜의 숲..🤐",
      answerText: "인내의 숲을 생각했지만.. 많이 달랐던...",
      errorTitle: "이걸 틀려..?🙄",
      errorText: "쉬어가는 문제인데 증말~~",
    },
    {
      date: "20241020",
      desc1: "2024.10.20",
      desc2: "다산로 나들이",
      logo: require("@/assets/img/logo/20241020.png"),
      map: require("@/assets/img/map_20241020.png"),
      map2: undefined,
      buttonText1: undefined,
      buttonText2: undefined,
      drive: "http://naver.me/G380jI5p",
      title: "TMI Quiz~~\n이날 결혼식을 올린 연예인은?",
      radio: {
        v1: "안재욱",
        v2: "조세호",
        v3: "류이서",
      },
      answer: "v2",
      answerTitle: "조세호씨 행복하게 사세요~🎊",
      answerText: "신라호텔은 축의금을 얼마나 내야할까....",
      errorTitle: "불참해서 잊어버릴 수도 있지~🔎",
      errorText: "모르는데 어떻게 가요??",
    },
    {
      date: "20241026",
      desc1: "2024.10.26",
      desc2: "용산 나들이",
      logo: require("@/assets/img/logo/20241026.png"),
      map: require("@/assets/img/map_20241026_1.png"),
      map2: require("@/assets/img/map_20241026_2.png"),
      buttonText1: "다녀온 경로는 어떨지..",
      buttonText2: "아이디어와는 너무 다른 경로..",
      drive: "http://naver.me/5UEzur2F",
      title: "서울 촌놈의 취향 저격이였던\n카페의 이름은~",
      radio: {
        v1: "스탠딩커피",
        v2: "웨스트빙고",
        v3: "만월경",
      },
      answer: "v2",
      answerTitle: "서빙고라 웨스트빙고~🤣",
      answerText: "너무 작명센스가 좋다 증말~~",
      errorTitle: "아직 취향을 모르는걸로...😥",
      errorText: "근데 이걸 모르네~ㅋㅋ",
    },
    {
      date: "20241102",
      desc1: "2024.11.02",
      desc2: "서래마을, 낙산공원 나들이",
      logo: require("@/assets/img/logo/20241102_1.png"),
      map: require("@/assets/img/map_20241102_1.png"),
      map2: require("@/assets/img/map_20241102_2.png"),
      buttonText1: "자율학습 경로도 궁금해~",
      buttonText2: "기존 코스도 다시 보여줘~",
      drive: "http://naver.me/5Kb16v4r",
      title: "자율학습을 위해 버스를 타고\n10월의 어느 날을 복습했을까요~",
      radio: {
        v1: "5일",
        v2: "13일",
        v3: "20일",
        v4: "26일",
      },
      answer: "v3",
      answerTitle: "한남동부터 약수역까지...🚌",
      answerText: "진짜 많이 걸었었더라...",
      errorTitle: "이걸 벌써 잊어먹었어??😒",
      errorText: "바깥구경을 덜했네~",
    },
    {
      date: "20241110",
      desc1: "2024.11.10",
      desc2: "서울어린이대공원 나들이",
      logo: require("@/assets/img/logo/20241110_2.png"),
      map: require("@/assets/img/map_20241110_2.png"),
      map2: require("@/assets/img/map_20241110_3.png"),
      buttonText1: "과연 아이디어대로 다녀왔을지?",
      buttonText2: "역시나 아이디어는 아이디어일 뿐이다~",
      drive: "http://naver.me/xVBWuVo0",
      title: "놀이공원에서부터 함께하며\n이날의 사진 요정은 누구일까요~",
      radio: {
        v1: "구데타마",
        v2: "폼폼푸린",
        v3: "시나모롤",
      },
      answer: "v1",
      answerTitle: "경품으로 우연히 만난 구데타마~",
      answerText: "가방에 달고 있어도 잘 어울리더라구요..^_^",
      errorTitle: "집에 잘 보관하실꺼라며요.....?",
      errorText: "퇴근 시켜드린건 아니죠.....?",
      // 질문 v1
      // title: "열심히 지하철을 타고...\n도착한 역의 이름은 무엇일까요~",
      // radio: {
      //   v1: "우장산역",
      //   v2: "아차산역",
      // },
      // answer: "v2",
      // answerTitle: "아차! 아차산역!",
      // answerText: "역시 당일이라 기억을 잘하네~",
      // errorTitle: "출발 말고....",
      // errorText: "집에 가고 싶으신건가..?",
    },
    {
      date: "20241123",
      desc1: "2024.11.23",
      desc2: "공주 나들이",
      logo: require("@/assets/img/logo/20241123.png"),
      map: require("@/assets/img/map_20241123.png"),
      map2: undefined,
      buttonText1: undefined,
      buttonText2: undefined,
      drive: "http://naver.me/GoD1Gqnz",
      title: "고마열차에서 내려서\n원래 어디를 가려했었을까요~?",
      radio: {
        v1: "금강교",
        v2: "공산성",
        v3: "중동성당",
      },
      answer: "v2",
      answerTitle: "5시까지 입장 제한이던...😥",
      answerText: "근데 찾아보니까 그냥 들어가더라...",
      errorTitle: "다 다녀온 곳이라 헷갈리나보다~😯",
      errorText: "5시에 문 닫던 곳 있잖아~",
    },
  ],
  getTrip(date) {
    const result = this.trips.find((item) => item.date === date);
    return result ? result : undefined;
  },
  getIsValid(date) {
    const result = this.trips.find((item) => item.date === date);
    return result ? 1 : 0;
  },
};

export const globalShoes = {
  brands: [
    {
      id: 1,
      brandId: "nb",
      divId: "nbBrandDiv",
      name: "뉴발란스",
      desc: "발 편한건 역시 뉴발란스지~",
      img: require("@/assets/img/shoes/NB.png"),
      shoes: [
        {
          id: 1,
          divId: "nb574Div",
          shoesId: "nb574",
          name: "뉴발란스 574",
          desc: "동글동글 괜찮잖아. 귀엽잖아..?",
          price: "149,000원",
          img: require("@/assets/img/shoes/NB574.png"),
          videoLink: undefined,
          videoDesc: undefined,
          video: undefined,
          shoesInfo1: "1988년 출시해 약 45년간 꾸준히 사랑받는 신발",
          shoesInfo2: "어디에 신어도 잘어울리는 귀여운 쉐입,,,",
          shoesInfo3: "더불어 오래 걸어다녀도 발이 안아픈 착화감,,,",
          shoesInfo4: "여러 색상도 보유해 원하는 색상을 마음대로 고를 수 있다는 장점까지~~",
          reviewImg1:
            "https://mblogthumb-phinf.pstatic.net/MjAyNDA1MTRfMjgy/MDAxNzE1NjcwNTQ3MDgx.V4PwWiMmhcPOQLiXxq2R4HTmSYMN0c7hwfRj5ZL09ZUg.rDGlsruOaKD5WH_3QjCHTsGAjAJM-LlZNjq331ffmL8g.PNG/capture-20240514-160043.png?type=w800",
          reviewDesc1: "아이유도 신는 그 신발,,,",
          reviewLink1: "https://m.blog.naver.com/bombo_m_/223444682914",
          reviewImg2: require("@/assets/img/shoes/NB574Review.png"),
          reviewDesc2: "한 블로거의 착용샷",
          reviewLink2: "https://blog.naver.com/dannilong/223593084057",
        },
        {
          id: 2,
          divId: "nb530Div",
          shoesId: "nb530",
          name: "뉴발란스 530",
          desc: "어디에 신어도 잘 어울리는 신발",
          price: "119,000원",
          img: require("@/assets/img/shoes/NB530.png"),
          videoLink: "https://www.youtube.com/watch?v=MfQbPgEFc_Q",
          videoDesc: "뉴발란스 화이팅~!(링크)",
          video: undefined,
          shoesInfo1: "한동안 품절 대란이였던 그 신발!",
          shoesInfo2: "여전히 특정 색은 구하기 어렵다는...",
          shoesInfo3: "뉴발란스 특유의 편한 착화감에 스타일까지",
          shoesInfo4: "메쉬 소재를 사용하여 가볍기까지!",
          reviewImg1: "https://contents-cdn.viewus.co.kr/image/2024/05/CP-2023-0018/image-8996b1ad-cd68-4ec5-af62-b4919c525992.jpeg",
          reviewDesc1: "오연서 인스타에 등장..",
          reviewLink1: "https://www.instagram.com/p/C6eH4VGyTR4/?img_index=7",
          reviewImg2: "https://contents-cdn.viewus.co.kr/image/2024/05/CP-2023-0018/image-cbc320d0-d584-4745-9048-6bf7fc8ed674.jpeg",
          reviewDesc2: "류이서 인스타에도 등장..",
          reviewLink2: "https://www.instagram.com/p/C5QMIdRuF_N/?img_index=3",
        },
      ],
    },
    {
      id: 2,
      brandId: "nike",
      divId: "nikeBrandDiv",
      name: "나이키",
      desc: "나이키가 한물 갔다해도 나이키지~",
      img: require("@/assets/img/shoes/Nike.png"),
      shoes: [
        {
          id: 1,
          divId: "nikeP6000Div",
          shoesId: "p6000",
          name: "P-6000",
          desc: "캐주얼 룩에 찰떡인 신발",
          price: "129,000원",
          img: require("@/assets/img/shoes/NikeP6000.png"),
          videoLink: undefined,
          videoDesc: undefined,
          video: undefined,
          shoesInfo1: "놀면 뭐하니에서 이효리가 신었던 신발",
          shoesInfo2: "이후 꾸준히 인기를 유지중~",
          shoesInfo3: "다른 추천 신발들에 비해 덜 유명하다는게 장점!",
          shoesInfo4: "",
          reviewImg1: "https://dnvefa72aowie.cloudfront.net/origin/article/202009/918EB231DC1C13D9A631934595073A04DB853A9437520A01200ADF1720932AE8.jpg?f=webp&q=95&s=1440x1440&t=inside",
          reviewDesc1: "이효리가 신었던 그 신발",
          reviewLink1: "https://www.youtube.com/watch?v=8RO5p0Y5roo",
          reviewImg2: "https://img.croket.co.kr/item/contents/3d399398a6fbca1a7e8103cb70014c09.jpeg",
          reviewDesc2: "정유미가 날려버린...",
          reviewLink2: "https://www.youtube.com/watch?v=N0i-OXXk930&list=PLgbB1gJhmG7A7LmzZmNz8KaLmiO1jsrLD&index=2",
        },
        {
          id: 2,
          divId: "nikeV2KDiv",
          shoesId: "v2k",
          name: "V2K 런",
          desc: "굉장히 인기가 많은 V2K",
          price: "139,000원",
          img: require("@/assets/img/shoes/NikeV2K.png"),
          videoLink: "https://youtu.be/KMIDJb942bc?si=CzpgAAaJaUP2OQe6",
          videoDesc: "참고 영상(링크)🎞",
          video: require("@/assets/video/mjV2K.mp4"),
          shoesInfo1: "2024년 나이키 신상!",
          shoesInfo2: "레트로 + 미래적 디자인 데일리 운동화로 찰떡~",
          shoesInfo3: "청키한 힐 덕분에 장거리 걷기에도 최적!",
          shoesInfo4: "전체 적으로 편안한 착화감의 신발!",
          reviewImg1:
            "https://mblogthumb-phinf.pstatic.net/MjAyNDAyMDVfMjYx/MDAxNzA3MDk5Njg2NTAw.Cs9v4hnCme2BwsaY9TRazVdMSfrRbVi75htz2iSEfhYg.XBNHZndpZezdCW0h4_WFZGRbMy8aBpZr5deuK6ixuCAg.JPEG.snh2003/%EC%9D%B4%EC%B2%AD%EC%95%84_%EB%82%98%EC%9D%B4%ED%82%A4_V2K%EB%9F%B0_%EC%97%AC%EC%84%B1_%EC%9A%B4%EB%8F%99%ED%99%94_0.jpg?type=w800",
          reviewDesc1: "여러 색상을 구매한 이청아",
          reviewLink1: "https://www.instagram.com/p/C6jLUs5x7a2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
          reviewImg2:
            "https://mblogthumb-phinf.pstatic.net/MjAyNDA2MThfMTAy/MDAxNzE4NzEzMTcwNDg0.5oz-sgkEOpRtSN6dA2C9keHN_zefcJedCdM767AKxjwg.AoywvLB9ICVCxEBMW-Ku0gpwYklB5_nat_b64knB3rMg.JPEG/1%EB%B0%95_2%EC%9D%BC_%EB%8F%84%EC%BF%84,_%EC%95%8C%EC%B0%BC%EB%8B%A4.%ED%95%98%EB%A3%A8%EC%97%90_16000%EB%B3%B4_%EA%B1%B7%EA%B3%A0_%EC%95%BC%EB%AC%B4%EC%A7%80%EA%B2%8C_%EB%A8%B9%EA%B3%A0,_%EB%B6%93%EA%B3%A0,%EC%9C%A0%ED%8A%9C%EB%B8%8C_%EC%97%B4%EC%8B%AC%ED%9E%88_%EC%B0%8D%EC%97%88%EB%8B%A4_(%EB%82%B4%EA%B0%80_%EC%B0%8D%EC%96%B4%EC%A3%BC%EB%8A%94_%EC%B9%9C%EA%B5%AC_%EB%A7%88%EC%A7%80%EB%A7%89%EC%82%AC%EC%A7%84_).jpg?type=w800",
          reviewDesc2: "윤승아가 16000보를 걸을때 신은 신발",
          reviewLink2: "https://www.instagram.com/p/C7-pgn5hupO/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
        },
        {
          id: 3,
          divId: "nikeZoomBomero5Div",
          shoesId: "zoombomero5",
          name: "줌 보메로5",
          desc: "뉴진스 민지의 추천 픽!",
          price: "189,000원",
          img: require("@/assets/img/shoes/NikeZoomBomero5.png"),
          videoLink: "https://youtu.be/KMIDJb942bc?si=CzpgAAaJaUP2OQe6",
          videoDesc: "참고 영상(링크)🎞",
          video: require("@/assets/video/mjZB5.mp4"),
          shoesInfo1: "요즘 대세 v2k의 선배님!",
          shoesInfo2: "과거 러닝화 기술을 적용해 편한 신발",
          shoesInfo3: "살짝 비싸지만... 못참고 추가",
          shoesInfo4: "(절대 민지의 추천 때문이 아님 😗)",
          reviewImg1:
            "https://mblogthumb-phinf.pstatic.net/MjAyNDA3MjRfMTkx/MDAxNzIxNzgyNTAwNjA4.4pqkeyQV1mFvKWlhhVE0dPgkcukskqtmQSMGCyWzEH8g.bUz2B8kJYhUFT5gRWXogWSEbkmb2auXlVeEQAnd3Fvkg.JPEG/%EB%82%98%EC%9D%B4%ED%82%A4_%EC%A4%8C_%EB%B3%B4%EB%A9%94%EB%A1%9C_5_%EB%B0%9C_%ED%8E%B8%ED%95%9C_%EC%97%AC%EC%9E%90_%EC%9A%B4%EB%8F%99%ED%99%94_%EC%B6%94%EC%B2%9C_%EC%97%B0%EC%98%88%EC%9D%B8_%EC%8A%A4%EB%8B%88%EC%BB%A4%EC%A6%88_%EB%B8%8C%EB%9E%9C%EB%93%9C_01.jpg?type=w800",
          reviewDesc1: "하트시그널3 김지영의 신발",
          reviewLink1: "https://www.instagram.com/p/C7d2LjAJKMU/?img_index=4",
          reviewImg2:
            "https://mblogthumb-phinf.pstatic.net/MjAyMzA0MjVfMjE3/MDAxNjgyNDIzNDkwMjYx.R_3tFuDW6YGSCNTISZ-oTX_ZDGxKBuRz_5LQhW15cXog.QNvPHt76GcOZsGaRZP4P_VOLG24v6At2cWIemxqUmhsg.JPEG.jhcjjang1696/%EB%82%98%EC%9D%B4%ED%82%A4_%EC%A4%8C_%EB%B3%B4%EB%A9%94%EB%A1%9C_5_%EC%98%B7_%EC%9E%98%EC%9E%85%EB%8A%94_%EC%97%AC%EC%9E%90_%EC%97%B0%EC%98%88%EC%9D%B8_%ED%8C%A8%EC%85%98_(7).jpg?type=w800",
          reviewDesc2: "이런 새로운 시도는...?",
          reviewLink2: "https://blog.naver.com/jhcjjang1696/223084978636",
        },
      ],
    },
    {
      id: 3,
      brandId: "asics",
      divId: "asicsBrandDiv",
      name: "아식스",
      desc: "요즘 MZ들 사이에서 핫한 아식스!",
      img: require("@/assets/img/shoes/Asics.png"),
      shoes: [
        {
          id: 1,
          divId: "asicsJog100Div",
          shoesId: "jog100",
          name: "조그 100",
          desc: "가성비하면 이 신발이지!",
          price: "79,000원",
          img: require("@/assets/img/shoes/AsicsJog100.png"),
          videoLink: undefined,
          videoDesc: undefined,
          video: undefined,
          shoesInfo1: "최근 MZ들 사이에서 유행하는 아식스",
          shoesInfo2: "특정 컬러는 구하기 어려운...",
          shoesInfo3: "가격도 저렴해 부담이 덜하다!",
          shoesInfo4: "쿠션감은 덜하지만 꽉잡아주는 느낌이 있다는 신발",
          reviewImg1: require("@/assets/img/shoes/AsicsJogReview.png"),
          reviewDesc1: "일반인의 코디",
          reviewLink1: "https://kream.co.kr/social/posts/1036186",
          reviewImg2: require("@/assets/img/shoes/AsicsJogReview2.png"),
          reviewDesc2: "블로거의 후기..",
          reviewLink2: "https://blog.naver.com/yunamaro/223216246826",
        },
      ],
    },
  ],
};
